services:
  - type: web
    name: nija-bot-web
    env: python
    plan: starter
    branch: main
    buildCommand: |
      python3 -m venv .venv
      source .venv/bin/activate
      python3 -m pip install --upgrade pip
      python3 -m pip install -r requirements.txt
    startCommand: .venv/bin/gunicorn --workers 1 --bind 0.0.0.0:$PORT nija_bot:app
    envVars:
      - key: API_KEY
        fromSecret: API_KEY
      - key: API_SECRET
        fromSecret: API_SECRET
      - key: LIVE_TRADING
        value: "False"
      - key: ADMIN_TOKEN
        fromSecret: ADMIN_TOKEN
      - key: AUTO_START
        value: "True"
