services:
  - type: web
    name: nija-trading-bot
    env: python
    plan: free
    buildCommand: .venv/bin/python -m pip install --upgrade --force-reinstall -r requirements.txt
startCommand: .venv/bin/python -m gunicorn -b 0.0.0.0:$PORT nija_bot:app
    envVars:
      - key: API_KEY
        value: your_api_key_here
      - key: API_SECRET
        value: your_api_secret_here
      - key: API_PEM_B64
        value: "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----"
      - key: TV_WEBHOOK_SECRET
        value: https://nija-trading-bot-9ja3.onrender.com/webhook
