services:
  - type: worker
    name: nija-bot-worker
    env: python
    buildCommand: "./build.sh"
    startCommand: ".venv/bin/python3 nija_bot.py"
    plan: free
    envVars:
      - key: API_KEY
        value: "<YOUR_API_KEY>"
      - key: API_SECRET
        value: "<YOUR_API_SECRET>"
      - key: LIVE_TRADING
        value: "False"
